[project]
name = "elasticsearch-course"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch==8.15.1",
    "fastapi==0.115.5",
    "fastapi-cli==0.0.5",
    "ranx==0.3.21",
    "sentence-transformers>=5.1.2",
    "tqdm==4.66.5",
    "uvicorn>=0.38.0",
]
